version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:80"  # Change the host port to 8080
    depends_on:
      - mysql
    networks:
      - laravel

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: task_management_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    networks:
      - laravel

  # Core PHP Service for CSV Reporting
  corephp:
    image: php:8.1-cli
    container_name: core_php
    volumes:
      - .:/var/www
    entrypoint: ["php", "/var/www/generate_report.php"]
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
