version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    networks:
      - task_management_net
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: task_management_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_management_db
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - task_management_net

  php-report:
    image: php:8.1-cli
    container_name: php_report
    volumes:
      - .:/var/www
    networks:
      - task_management_net
    entrypoint: ["php", "/var/www/report.php"]

networks:
  task_management_net:
    driver: bridge
